version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5043:80"
    depends_on:
      - backend
    networks:
      - mysql_networks

  backend:
    command:
    build:
      context: ./webapi/backend
      dockerfile: Dockerfile
    ports:
      - "5040:8080"
      - "5041:8081"
    depends_on:
      - mysql
    networks:
      - mysql_networks

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    container_name: mysql
    image: mysql:8.1
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    networks:
      - mysql_networks

volumes:
  mysql_volume:

networks:
  mysql_networks:
    driver: bridge
